/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import Services.UserService;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Jázsi
 */
public class Login extends javax.swing.JFrame {

    private UserService userService;
    private Register register;

    /**
     * Creates new form NewJFrameLogin
     */
    public Login() {
        this.userService = new UserService();
        initComponents();
        jButton1LogIn.setEnabled(false);
        this.userService.readAlltheUser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1LogIn = new javax.swing.JButton();
        jPasswordField1Login = new javax.swing.JPasswordField();
        jTextField1EmailLogin = new javax.swing.JTextField();
        jLabelErrorLogin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2SignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zifar ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 21, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Zifar");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shajinder\\Desktop\\Dam 2\\Acceso Datos\\Actividad_Evaluativa_Jaskaran_Singh\\resources\\imagenes\\Logotipo minimalista inmobiliaria edificios amarillo y azul (2).png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 370, 290));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 450, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 21, 48));
        jLabel6.setText("Zifar");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton1LogIn.setBackground(new java.awt.Color(1, 21, 48));
        jButton1LogIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1LogIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton1LogIn.setText("Log in");
        jButton1LogIn.setAlignmentX(0.5F);
        jButton1LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1LogIn.setEnabled(false);
        jButton1LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LogInActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 40));

        jPasswordField1Login.setBackground(new java.awt.Color(250, 250, 250));
        jPasswordField1Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1Login.setText("*******"); // NOI18N
        jPasswordField1Login.setToolTipText("");
        jPasswordField1Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jPasswordField1Login.setName(""); // NOI18N
        jPasswordField1Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1LoginMousePressed(evt);
            }
        });
        jPasswordField1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1LoginActionPerformed(evt);
            }
        });
        jPasswordField1Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1LoginKeyReleased(evt);
            }
        });
        jPanel3.add(jPasswordField1Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, 40));
        jPasswordField1Login.getAccessibleContext().setAccessibleName("");

        jTextField1EmailLogin.setBackground(new java.awt.Color(250, 250, 250));
        jTextField1EmailLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1EmailLogin.setText("Email");
        jTextField1EmailLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jTextField1EmailLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1EmailLoginMousePressed(evt);
            }
        });
        jTextField1EmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1EmailLoginActionPerformed(evt);
            }
        });
        jTextField1EmailLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1EmailLoginKeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1EmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 40));

        jLabelErrorLogin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelErrorLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelErrorLogin.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabelErrorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 320, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 380, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("You do not have an account?");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 30));

        jButton2SignUp.setBackground(new java.awt.Color(255, 255, 255));
        jButton2SignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2SignUp.setForeground(new java.awt.Color(1, 21, 48));
        jButton2SignUp.setText("Sign up ");
        jButton2SignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2SignUp.setBorderPainted(false);
        jButton2SignUp.setContentAreaFilled(false);
        jButton2SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SignUpActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 90, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 380, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1LoginActionPerformed
        // TODO add your handling code here:
        jButton1LogIn.setEnabled(true);
    }//GEN-LAST:event_jPasswordField1LoginActionPerformed

    private void jTextField1EmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1EmailLoginActionPerformed
        // TODO add your handling code here:
        jButton1LogIn.setEnabled(true);
    }//GEN-LAST:event_jTextField1EmailLoginActionPerformed

    private void jButton1LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LogInActionPerformed
        // TODO add your handling code here:
        String email = this.jTextField1EmailLogin.getText();
        String password = String.valueOf(this.jPasswordField1Login.getPassword());
        if (this.userService.checkEmail(email)) {
            LocalDateTime time = LocalDateTime.now();
           this.userService.checkLasTimeLoginAndSetTheAttempts(email,time);
            checkTheAttemptsAndThePassword(email,password);
        } else {
            this.jLabelErrorLogin.setText("The email does not exist");
        }
    }//GEN-LAST:event_jButton1LogInActionPerformed
    /**
     * Métood que llama a sumar intentos y luego los escribe 
     * @param email String
     */
    public void plusTheAttemptsAndShowError(String email) {
        this.userService.plusTheAttempts(email);
        LocalDateTime time = LocalDateTime.now();
        this.userService.setLastTimeLogIn(email, time);
        this.userService.writeUsers();
        this.jLabelErrorLogin.setText("The password is not correct please try again");
        jPasswordField1Login.setText("");
    }
    
    /**
     * Método que comprueba los intentos y la contraseña
     * @param email String 
     * @param password String
     */
    public void checkTheAttemptsAndThePassword(String email, String password) {
        if (this.userService.checkAttempts(email)) {
            JOptionPane.showMessageDialog(null, "You have exceeded the maximum amount of times you can login come back after 24 hours");
        } else if (this.userService.checkPassword(email, password)) {
            LocalDateTime time = LocalDateTime.now();
            this.userService.setLastTimeLogIn(email, time);
            this.userService.writeUsers();
            ShowUsers showUSers = new ShowUsers(this.userService);
            showUSers.setVisible(true);
            this.dispose();
        } else {
            plusTheAttemptsAndShowError(email);
        }

    }
    private void jButton2SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SignUpActionPerformed
        // TODO add your handling code here:
        this.register = new Register(this.userService);
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2SignUpActionPerformed

    private void jTextField1EmailLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1EmailLoginKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1EmailLoginKeyReleased

    private void jPasswordField1LoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1LoginKeyReleased
        // TODO add your handling code here:
        this.jButton1LogIn.setEnabled(true);
    }//GEN-LAST:event_jPasswordField1LoginKeyReleased

    private void jTextField1EmailLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1EmailLoginMousePressed
        // TODO add your handling code here:
        if (jTextField1EmailLogin.getText().equals("Email")) {
            jTextField1EmailLogin.setText("");
        }
    }//GEN-LAST:event_jTextField1EmailLoginMousePressed

    private void jPasswordField1LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1LoginMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1Login.getPassword()).equals("*******")) {
            jPasswordField1Login.setText("");
        }
    }//GEN-LAST:event_jPasswordField1LoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1LogIn;
    private javax.swing.JButton jButton2SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelErrorLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1Login;
    private javax.swing.JTextField jTextField1EmailLogin;
    // End of variables declaration//GEN-END:variables
}
