/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import Services.SendEmail;
import Services.UserService;
import classes.LogInUser;
import java.util.UUID;

/**
 *
 * @author Jázsi
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameRegister
     */
    private UserService userService;
    private SendEmail emailSender;

    public Register(UserService userService) {
        initComponents();
        this.userService = new UserService();
        this.userService.readAlltheUser();
        this.emailSender = new SendEmail();

    }
    /**
     * Método que crea los usuarios y luego los mete en el array
     */
    public void createUserAndAddToTheArray() {
        UUID idOne = UUID.randomUUID();
        String email = jTextFieldEmail.getText();
        String userName = jTextFieldUsername.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        int postCode = Integer.valueOf(jTextField1PostCode.getText());
        int age = Integer.valueOf((String) jComboBox1.getSelectedItem());
        String id = String.valueOf(idOne);
        LogInUser loginUser = new LogInUser();
        this.userService.createUsers(email, userName, password, age, postCode, id, loginUser);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPostCode = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        jTextField1PostCode = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register on Zifar");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 21, 48));
        jLabel6.setText("Zifar");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelPostCode.setBackground(new java.awt.Color(255, 0, 0));
        jLabelPostCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPostCode.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPostCode.setToolTipText("");
        jPanel3.add(jLabelPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 20));

        jButton1.setBackground(new java.awt.Color(1, 21, 48));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register ");
        jButton1.setAlignmentX(0.5F);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 310, 40));

        jPasswordField1.setBackground(new java.awt.Color(250, 250, 250));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setText("*******"); // NOI18N
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jPasswordField1.setName(""); // NOI18N
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 310, 40));

        jTextFieldUsername.setBackground(new java.awt.Color(250, 250, 250));
        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsername.setText("Username");
        jTextFieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jTextFieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldUsernameMousePressed(evt);
            }
        });
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 40));

        jComboBox1.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "100" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 40));

        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(1, 21, 48));
        label1.setText("Age");
        jPanel3.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 60, 30));

        jTextField1PostCode.setBackground(new java.awt.Color(250, 250, 250));
        jTextField1PostCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1PostCode.setText("Post code");
        jTextField1PostCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jTextField1PostCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1PostCodeMousePressed(evt);
            }
        });
        jTextField1PostCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1PostCodeKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField1PostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 310, 40));

        jLabelEmail.setBackground(new java.awt.Color(255, 0, 0));
        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 30));

        jTextFieldEmail.setBackground(new java.awt.Color(250, 250, 250));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEmail.setText("Email");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMousePressed(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped1(evt);
            }
        });
        jPanel3.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, 40));

        jLabelUsername.setBackground(new java.awt.Color(255, 0, 0));
        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 390, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.userService.checkEmail(this.jTextFieldEmail.getText())) {
            this.jLabelEmail.setText("This email already exists");
        } else if (this.userService.checkUsername(this.jTextFieldUsername.getText())) {
            this.jLabelUsername.setText("This username already exists");
        } else if (!this.userService.checkIfTheEmailIsValid(this.jTextFieldEmail.getText())) {
            this.jLabelEmail.setText("This email is no valid");
        } else {
            createUserAndGoToLogin();
            emailSender.createEmail(this.jTextFieldEmail.getText());
            emailSender.sendEmail();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * Método que crea el usuario y vuelve al menú del log in
    */
    public void createUserAndGoToLogin() {
        createUserAndAddToTheArray();
        this.userService.readAlltheUser();
        this.userService.writeUsers();
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);

    }
    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped


    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    private void jTextFieldUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsernameMousePressed
        // TODO add your handling code here:
        if (jTextFieldUsername.getText().equals("Username")) {
            this.jTextFieldUsername.setText("");
        }
    }//GEN-LAST:event_jTextFieldUsernameMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("*******")) {
            this.jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MousePressed
    /**
     * @param evt
     */
    private void jTextField1PostCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1PostCodeKeyTyped

        char character = evt.getKeyChar();
        if (!Character.isDigit(character)) {
            this.jLabelPostCode.setText("You only can enter numbers here");
            evt.consume();
        } else {
            this.jLabelPostCode.setText("");
        }
    }//GEN-LAST:event_jTextField1PostCodeKeyTyped

    private void jTextField1PostCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1PostCodeMousePressed
        // TODO add your handling code here:
        this.jTextField1PostCode.setText("");
        this.jButton1.setEnabled(true);
    }//GEN-LAST:event_jTextField1PostCodeMousePressed

    private void jTextFieldEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMousePressed
        // TODO add your handling code here:
        if (jTextFieldEmail.getText().equals("Email")) {
            this.jTextFieldEmail.setText("");
        }
    }//GEN-LAST:event_jTextFieldEmailMousePressed

    private void jTextFieldEmailKeyTyped1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped1
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldEmailKeyTyped1

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPostCode;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1PostCode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldUsername;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
